version: '3'
services:
  stellar-core-postgres:
    image: postgres:10
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stellar-core
      - POSTGRES_PASSWORD=RonUQgj23En5Mmo4

  stellar-core:
    image: satoshipay/stellar-core:dev-vogel-publish-command-1
    restart: on-failure
    volumes:
      - core-data:/data
    environment:
      - DATABASE=postgresql://dbname=stellar-core user=postgres password=DATABASE_PASSWORD host=stellar-core-postgres
      - DATABASE_PASSWORD=RonUQgj23En5Mmo4
      - INITIALIZE_DB=false
      - INITIALIZE_HISTORY_ARCHIVES=false
      # public key GACVY6FX6ZSGBEWQF6DG25VOAB25F72EI4WS676QIO3HO2YBKAKDI44H
      - NODE_SEED=SDEZOI3BOCW6DUY23ZCJQALULOIEIQMZW4UTFXPRQEMMJMOG7CVD7WMO catchup
      - NODE_IS_VALIDATOR=true
      - NETWORK_PASSPHRASE=Public Global Stellar Network ; September 2015
      - MAX_PEER_CONNECTIONS=30
      - "KNOWN_PEERS=\
        au.stellar.ibm.com,\
        br.stellar.ibm.com,\
        ca.stellar.ibm.com,\
        no.stellar.ibm.com,\
        it.stellar.ibm.com,\
        hk.stellar.ibm.com,\
        in.stellar.ibm.com,\
        uk.stellar.ibm.com,\
        us.stellar.ibm.com,\
        stellar-de-fra.satoshipay.io,\
        stellar-sg-sin.satoshipay.io,\
        stellar-us-iowa.satoshipay.io,\
        core-live-a.stellar.org,\
        core-live-b.stellar.org,\
        core-live-c.stellar.org"
      - "PREFERRED_PEERS=\
        au.stellar.ibm.com,\
        br.stellar.ibm.com,\
        ca.stellar.ibm.com,\
        no.stellar.ibm.com,\
        it.stellar.ibm.com,\
        hk.stellar.ibm.com,\
        in.stellar.ibm.com,\
        uk.stellar.ibm.com,\
        us.stellar.ibm.com,\
        stellar-de-fra.satoshipay.io,\
        stellar-sg-sin.satoshipay.io,\
        stellar-us-iowa.satoshipay.io,\
        core-live-a.stellar.org,\
        core-live-b.stellar.org,\
        core-live-c.stellar.org"
      - "NODE_NAMES=\
        GCKWUQGSVO45ZV3QK7POYL7HMFWDKWJVMFVEGUJKCAEVUITUCTQWFSM6 ibm_au,\
        GBUJA3Z5TLAKLI5MEH4TETLXJBQVSVW74MNEKP5UUHTP3IMLNSUPOTVA ibm_br,\
        GB2HF2NHRKKFZYFDGD7MUENOYROOEK7SWYV2APYOODP6P7BUJTLILKIL ibm_ca,\
        GDRA72H7JWXAXWJKOONQOPH3JKNSH5MQ6BO5K74C3X6FO2G3OG464BPU ibm_no,\
        GAEEH4TBR7YQQWKJ2FIT57HXZZTMK2BX5LY4POJUYFSEZ7Y2ONHPPTES ibm_it,\
        GBJ7T3BTLX2BP3T5Q4256PUF7JMDAB35LLO32QRDYE67TDDMN7H33GGE ibm_hk,\
        GCH3O5PTCZVR4G65W3B4XDKWI5V677HQB3QO7CW4YPVYDDFBE2GE7G6V ibm_in,\
        GAENPO2XRTTMAJXDWM3E3GAALNLG4HVMKJ4QF525TR25RI42YPEDULOW ibm_uk,\
        GARBCBH4YSHUJLYEPKEPMVYZIJ3ZSQR3QCJ245CWGY64X72JLN4A6RSG ibm_us,\
        GC5SXLNAM3C4NMGK2PXK4R34B5GNZ47FYQ24ZIBFDFOCU6D4KBN4POAE satoshipay-de-fra,\
        GBJQUIXUO4XSNPAUT6ODLZUJRV2NPXYASKUBY4G5MYP3M47PCVI55MNT satoshipay-sg-sin,\
        GAK6Z5UVGUVSEK6PEOCAYJISTT5EJBB34PN3NOLEQG2SUKXRVV2F6HZY satoshipay-us-iowa,\
        GCGB2S2KGYARPVIA37HYZXVRM2YZUEXA6S33ZU5BUDC6THSB62LZSTYH sdf_watcher1,\
        GCM6QMP3DLRPTAZW2UZPCPX2LF3SXWXKPMP3GKFZBDSF3QZGV2G5QSTK sdf_watcher2,\
        GABMKJM6I25XI4K7U6XWMULOUQIQ27BCTMLS6BYYSOWKTBUXVRJSXHYQ sdf_watcher3,\
        GAOO3LWBC4XF6VWRP5ESJ6IBHAISVJMSBTALHOQM2EZG7Q477UWA6L7U eno"
      - >-
          QUORUM_SET=[
            {
              "threshold_percent": 66,
              "validators": [
                "$$satoshipay-de-fra",
                "$$satoshipay-sg-sin",
                "$$satoshipay-us-iowa",
                "$$sdf_watcher1",
                "$$sdf_watcher2",
                "$$sdf_watcher3",
                "$$eno"
              ]
            }
          ]
      - KNOWN_CURSORS=HORIZON
      - >-
          HISTORY={
            "satoshipay-de-fra": {"get": "curl -sf https://stellar-history-de-fra.satoshipay.io/{0} -o {1}"},
            "satoshipay-sg-sin": {"get": "curl -sf https://stellar-history-sg-sin.satoshipay.io/{0} -o {1}"},
            "satoshipay-us-iowa": {"get": "curl -sf https://stellar-history-us-iowa.satoshipay.io/{0} -o {1}"},
            "sdf1": {"get": "curl -sf http://history.stellar.org/prd/core-live/core_live_001/{0} -o {1}"},
            "sdf2": {"get": "curl -sf http://history.stellar.org/prd/core-live/core_live_002/{0} -o {1}"},
            "sdf3": {"get": "curl -sf http://history.stellar.org/prd/core-live/core_live_003/{0} -o {1}"},
            "local": {
              "get": "cp /data/history/{0} {1}",
              "put": "cp {0} /data/history/{1}",
              "mkdir": "mkdir -p /data/history/{0}"
            }
          }

volumes:
  db-data:
  core-data:
